### ISSUE TITLE
Bug in mantastic script

### ISSUE THREAD

**Issue by BigCatStudio** [lbdyck/prompters#1]
Line 108 has bug that exits script when given any string. It happens because if checks for non-empty string:
if [ -n "$ARG" ]; then
   echo 'No search entered - try again...'
   exit 0
fi

It should be changed to -z.

**Comment by lbdyck** [comment]
Using `-n` works for me

**Comment by BigCatStudio** [comment]
Interesting, when i run `./mantastic <phrase>` or `./mantastic` and then provide phrase it does not work. Is there other method?

**Comment by lbdyck** [comment]
you are correct - fixing now

**Comment by lbdyck** [comment]
arg - if you enter `.mantastic` and then enter nothing at the prompt then it fall thru - not what is wanted.  Need a better solution.

**Comment by lbdyck** [comment]
this is where the issue is - if no argument it is not being detected by the `if [ -z` and falls thru and the `if [ -n "$ARG"` does not detect it is empty.

arg

```
if [ -z "$ARG" ]; then
   echo 'No search entered - try again...'
   exit 0
fi

#----------------------------------------------------------------#
# If only 1 argument then do a search                            #
#----------------------------------------------------------------#
if [ -n "$ARG" ]; then
   MAN=$(gum choose $(man -k $ARG | cut -d" " -f1 | tail -n +1) \
     --header "Select Man Page to View" --header.foreground="11")
   MAN=$(echo $MAN | cut -d" " -f1)
else
   MAN=$ARG
fi
```

**Comment by BigCatStudio** [comment]
If i understand correctly you want your program to ensure that user provides phrase. I changed checking if argument is empty in loop:
`#----------------------------------------------------------------#
# Check for zero arguments and prompt if none                    #
#----------------------------------------------------------------#

ARG=""

if [ "$#" -eq 0 ]; then
   while [ -z "$ARG" ]; do
      ARG=$(gum input --prompt "Enter a command for a manpage or a word to search for:" \
      --placeholder="e.g. ssh" --value="" --header.foreground="11")
   done
else
    ARG=$1
fi

# if [ -z "$ARG" ]; then
#    echo 'No search entered - try again...'
#    exit 0
# fi`

It works just fine and obviously this if statement:`if [ "$#" -le 1 ]; then` will always return true

**Comment by BigCatStudio** [comment]
If i understand correctly you want your program to ensure that user provides phrase. I changed checking if argument is empty in loop:
`#----------------------------------------------------------------#
#Check for zero arguments and prompt if none#
#----------------------------------------------------------------#

ARG=""

if [ "$#" -eq 0 ]; then
    while [ -z "$ARG" ]; do
        ARG=$(gum input --prompt "Enter a command for a manpage or a word to search for:"
        --placeholder="e.g. ssh" --value="" --header.foreground="11")
    done
else
    ARG=$1
fi

if [ -z "$ARG" ]; then
    echo 'No search entered - try again...'
    exit 0
fi`

It works just fine and obviously this if statement: `if [ "$#" -le 1 ]; then` will always return true

**Comment by BigCatStudio** [comment]
If i understand correctly you want your program to ensure that user provides phrase. I changed checking if argument is empty in loop:
```
#----------------------------------------------------------------#
#Check for zero arguments and prompt if none#
#----------------------------------------------------------------#

ARG=""

if [ "$#" -eq 0 ]; then
    while [ -z "$ARG" ]; do
        ARG=$(gum input --prompt "Enter a command for a manpage or a word to search for:"
        --placeholder="e.g. ssh" --value="" --header.foreground="11")
    done
else
    ARG=$1
fi

if [ -z "$ARG" ]; then
    echo 'No search entered - try again...'
    exit 0
fi
```

It works just fine and obviously this if statement: `if [ "$#" -le 1 ]; then` will always return true

**Comment by lbdyck** [comment]
seems like an infinite loop unless the user enters something - what's the escape?

**Comment by BigCatStudio** [comment]
Yes you are right, maybe adding some check for special phrase that quits program would be right. CTRL+C is bugging for some reason.

**Comment by lbdyck** [comment]
try what is there - i don't think there is a need for a loop - my 0.22 seems fine for now (i could be wrong)

btw. try the escape key instead of control-c

**Comment by BigCatStudio** [comment]
It works, thanks!
